filter:
    paths: [ 'lib/*' ]
    excluded_paths:
        - lib/Tests/*

tools:
    external_code_coverage: true
    php_code_sniffer:
        config: { standard: 'PSR1' }
    php_changetracking: true
    php_cpd: true
    php_cs_fixer:
        config: { level: 'psr1' }
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

coding_style:
    php:
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
        spaces:
            other:
                after_type_cast: true

checks:
    php:
        code_rating: true
        duplication: true
        no_goto: true
        simplify_boolean_return: true
        newline_at_end_of_file: true
        function_in_camel_caps: true
        classes_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        avoid_unnecessary_concatenation: true
        avoid_perl_style_comments: true
