language: php

branches:
    only:
        - master

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
    include:
        - php: 5.6
        - php: nightly
        - php: hhvm-nightly
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

notifications:
    slack:
        secure: kireALpefhfrVR4bcpZU1WL3U584m98uO29bjkZt4720hNsgr+t0ryZZIZfF5lIBZqF9ynGO3IIfRqdqaeyof0/s5YxCLtMO7/it0eeVgo/nmUbf4aMdrkb+nGwEepBN7XNkgFF9kxfoWfIEOWhlRYOdyJLgYiVNulnhyLsE0m4=

before_install:
    - mkdir -p build/logs
    - mkdir -p bin

install:
    - travis_retry composer self-update
    - travis_retry composer clear-cache
    - travis_retry composer install --no-interaction || travis_retry composer update --no-interaction

script:
    - bin/phpunit --verbose --configuration phpunit.xml.dist

after_script:
    - bin/coveralls -c .coveralls.yml -vvv
    - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
